export  const queryInfoConfig = {
  labelWidth: "120px",
  itemLayout: {
    padding: "10px 40px",
  },
  colLayout: {
    span: 8,
  },
  searchItem: [
    {
      field: "staff_id",
      type: "input",
      label: "ID",
      placeholder: "请输入身份证号",
    },
    {
      field: "staff_name",
      type: "input",
      label: "姓名",
      placeholder: "请输入姓名",
    },
    {
      field: "staff_manager_id",
      type: "input",
      label: "经理身份证号",
      placeholder: "经理身份证号",
    },
    {
      field: "staff_startwork_date",
      type: "datepicker",
      label: "创建时间",
      otherOptions: {
        startPlaceholder: "开始时间",
        endPlaceholder: "结束时间",
        type: "daterange",
      },
    },
    {
      field: "staff_department_number",
      type: "input",
      label: "部门号",
      placeholder: "部门号",
    },
    {
      field: "staff_phone",
      type: "input",
      label: "电话号码",
      placeholder: "电话号",
    },
    {
      field: "staff_address",
      type: "input",
      label: "地址",
      placeholder: "地址",
    },
    {
      field: "staff_work_branch",
      type: "input",
      label: "所在支行",
      placeholder: "所在支行",
    },
  ],
  checkItem: [
    {
      field: "num",
      type: "input",
      label: "请求数据量",
      placeholder: "请输入请求数据量",
    },
    {
      field: "page",
      type: "input",
      label: "当前页数",
      placeholder: "请输入当前页数",
    },
    {
      field: "staff_id",
      type: "input",
      label: "员工身份证号",
      placeholder: "员工身份证号",
    },
    {
      field: "staff_name",
      type: "input",
      label: "员工姓名",
      placeholder: "员工姓名",
    },
    {
      field: "staff_manager_id",
      type: "input",
      label: "经理身份证号",
      placeholder: "经理身份证号",
    },
    {
      field: "staff_startwork_date",
      type: "input",
      label: "入职日期",
      placeholder: "入职日期",
    },
    {
      field: "staff_department_number",
      type: "input",
      label: "部门号",
      placeholder: "部门号",
    },
    {
      field: "staff_phone",
      type: "input",
      label: "电话号码",
      placeholder: "电话号码",
    },
    {
      field: "staff_address",
      type: "input",
      label: "住址",
      placeholder: "住址",
    },
    {
      field: "staff_work_branch",
      type: "input",
      label: "所在支行",
      placeholder: "所在支行",
    }
  ],
  updateItem: [
    {
      field: "old_staff_id",
      type: "input",
      label: "旧·员工身份证号",
      placeholder: "旧·员工身份证号",
    },
    {
      field: "staff_id",
      type: "input",
      label: "员工身份证号",
      placeholder: "员工身份证号",
    },
    {
      field: "staff_name",
      type: "input",
      label: "员工姓名",
      placeholder: "员工姓名",
    },
    {
      field: "staff_manager_id",
      type: "input",
      label: "经理身份证号",
      placeholder: "经理身份证号",
    },
    {
      field: "staff_startwork_date",
      type: "input",
      label: "入职日期",
      placeholder: "入职日期",
    },
    {
      field: "staff_phone",
      type: "input",
      label: "电话号码",
      placeholder: "电话号码",
    },
    {
      field: "staff_address",
      type: "input",
      label: "住址",
      placeholder: "住址",
    },
    {
      field: "staff_work_branch",
      type: "input",
      label: "所在支行",
      placeholder: "所在支行",
    },
    {
      field: "staff_department_number",
      type: "input",
      label: "部门号",
      placeholder: "部门号",
    },
  ],
  deleteItem: [
    {
      field: "staff_id",
      type: "input",
      label: "	员工身份证号",
      placeholder: "员工身份证号",
    },
    {
      field: "staff_name",
      type: "input",
      label: "员工姓名",
      placeholder: "员工姓名",
    },
    {
      field: "staff_manager_id",
      type: "input",
      label: "经理身份证号",
      placeholder: "经理身份证号",
    },
    {
      field: "staff_startwork_date",
      type: "input",
      label: "入职日期",
      placeholder: "入职日期",
    },
    {
      field: "staff_department_number",
      type: "input",
      label: "部门号",
      placeholder: "部门号",
    },
    {
      field: "staff_phone",
      type: "input",
      label: "电话号码",
      placeholder: "电话号码",
    },
    {
      field: "staff_address",
      type: "input",
      label: "住址",
      placeholder: "住址",
    },
    {
      field: "staff_work_branch",
      type: "input",
      label: "所在支行",
      placeholder: "所在支行",
    },
  ],
  // listData:[
  //   {
  //     staff_id: '2016-05-03',
  //     staff_name: 'Tom',
  //     staff_manager_id: 'No. 189, Grove St, Los Angeles',
  //     staff_startwork_date: 'Tom',
  //     staff_department_number: 'Tom',
  //     staff_phone: 'Tom',
  //     staff_address: 'Tom',
  //     staff_work_branch: 'Tom',
  //   },
  //   {
  //     staff_id: '2016-05-03',
  //     staff_name: 'Tom',
  //     staff_manager_id: 'No. 189, Grove St, Los Angeles',
  //     staff_startwork_date: 'Tom',
  //     staff_department_number: 'Tom',
  //     staff_phone: 'Tom',
  //     staff_address: 'Tom',
  //     staff_work_branch: 'Tom',
  //   },{
  //     staff_id: '2016-05-03',
  //     staff_name: 'Tom',
  //     staff_manager_id: 'No. 189, Grove St, Los Angeles',
  //     staff_startwork_date: 'Tom',
  //     staff_department_number: 'Tom',
  //     staff_phone: 'Tom',
  //     staff_address: 'Tom',
  //     staff_work_branch: 'Tom',
  //   },
  //   {
  //     staff_id: '2016-05-03',
  //     staff_name: 'Tom',
  //     staff_manager_id: 'No. 189, Grove St, Los Angeles',
  //     staff_startwork_date: 'Tom',
  //     staff_department_number: 'Tom',
  //     staff_phone: 'Tom',
  //     staff_address: 'Tom',
  //     staff_work_branch: 'Tom',
  //   }
  // ],
  proplist:[
    { prop: 'staff_id', label: '员工身份证号', minWidth: '100' },
    { prop: 'staff_name', label: '员工姓名', minWidth: '100' },
    { prop: 'staff_manager_id', label: '经理身份证号', minWidth: '100' },
    { prop: 'staff_startwork_date', label: '入职日期', minWidth: '100' },
    { prop: 'staff_department_number', label: '部门号', minWidth: '100' },
    { prop: 'staff_phone', label: '电话号码', minWidth: '100' },
    { prop: 'staff_address', label: '住址', minWidth: '100' },
    { prop: 'staff_work_branch', label: '所在支行', minWidth: '100' }
    
  ],
  showIndexColumn:true,
  showSelectColum:true
};
